// names.config.js - the name substitution table (fmSearchResults "Bob finds
// Robert"). Each group is one set of names that mean the same person. A
// search word that equals any member of a group also matches every other
// member, as a whole word, and the result says so ("bob, also as robert").
//
// Deterministic: the list is data, not a model. Override or extend it by
// writing data/names.json as an array of arrays; that file REPLACES this one.
// Keep entries lower case, accents optional (both sides are normalized).

export const DEFAULT_NAME_GROUPS = [
  ["robert", "bob", "bobby", "rob", "robbie", "roberto", "bert"],
  ["margaret", "peg", "peggy", "maggie", "meg", "marge", "margo", "rita", "greta", "daisy"],
  ["william", "bill", "billy", "will", "willy", "liam", "wilhelm", "guillaume", "guillermo"],
  ["richard", "dick", "rick", "ricky", "rich", "ricardo", "riccardo"],
  ["elizabeth", "liz", "beth", "betty", "eliza", "lisa", "libby", "elisabeth", "isabel", "isabella", "elisabetta"],
  ["james", "jim", "jimmy", "jamie", "jacques", "giacomo", "jaime", "diego", "seamus"],
  ["john", "jack", "johnny", "jon", "jean", "juan", "giovanni", "johann", "hans", "ioannis", "yannis", "ivan", "sean", "ian", "evan"],
  ["matthew", "matt", "matthias", "mathias", "matias", "mateo", "matteo", "matthieu", "matias", "ματιας", "ματθαιος", "матвей", "метт"],
  ["michael", "mike", "mick", "mickey", "michel", "miguel", "michele", "mikhail", "michalis", "michail"],
  ["thomas", "tom", "tommy", "thom", "tomas", "tommaso", "thanasis"],
  ["charles", "charlie", "chuck", "chas", "carl", "karl", "carlos", "carlo", "karol"],
  ["edward", "ed", "eddie", "ted", "teddy", "ned", "eduardo", "edoardo", "edouard"],
  ["joseph", "joe", "joey", "jose", "giuseppe", "josef", "yusuf", "iosif"],
  ["anthony", "tony", "antonio", "anton", "antoine", "antonis", "antonios"],
  ["daniel", "dan", "danny", "danilo", "daniele"],
  ["david", "dave", "davey", "davide", "dawid"],
  ["christopher", "chris", "kit", "cristopher", "christoph", "cristobal", "christos", "christophe"],
  ["nicholas", "nick", "nicky", "nico", "nicolas", "niccolo", "nikolaos", "nikos", "nikolai", "klaus"],
  ["alexander", "alex", "alec", "sasha", "alessandro", "alejandro", "alexandros", "alexandre"],
  ["andrew", "andy", "drew", "andrea", "andres", "andre", "andreas", "andrei"],
  ["peter", "pete", "pietro", "pedro", "pierre", "petros", "piotr", "petr"],
  ["stephen", "steven", "steve", "stevie", "stefan", "stefano", "esteban", "stephanos", "stefanos"],
  ["george", "georg", "giorgio", "jorge", "georges", "giorgos", "yorgos", "georgios", "yuri"],
  ["henry", "hank", "harry", "hal", "enrique", "enrico", "heinrich", "henri"],
  ["frederick", "fred", "freddy", "friedrich", "fritz", "federico", "frederic"],
  ["benjamin", "ben", "benny", "benjamin", "beniamino"],
  ["samuel", "sam", "sammy", "samuele"],
  ["theodore", "ted", "teddy", "theo", "teodoro", "theodoros", "thodoris"],
  ["timothy", "tim", "timmy", "timoteo"],
  ["gerald", "gerry", "jerry", "geraldo"],
  ["lawrence", "larry", "laurence", "lorenzo", "laurent"],
  ["raymond", "ray", "raimondo", "ramon"],
  ["walter", "walt", "wally", "gualtiero"],
  ["donald", "don", "donny"],
  ["ronald", "ron", "ronnie"],
  ["kenneth", "ken", "kenny"],
  ["patrick", "pat", "paddy", "patrizio", "patricio", "patrice"],
  ["francis", "frank", "frankie", "francesco", "francisco", "francois", "franz", "paco"],
  ["paul", "paolo", "pablo", "pavlos", "pavel"],
  ["mark", "marc", "marco", "marcos", "markos", "marek"],
  ["luke", "luca", "lucas", "lukas", "loukas"],
  ["gregory", "greg", "gregg", "gregorio", "gregor", "grigoris"],
  ["konstantinos", "kostas", "costas", "constantine", "konstantin", "dinos"],
  ["dimitrios", "dimitris", "demetrios", "jim", "mitsos", "dmitri"],
  ["vasilios", "vasilis", "basil", "bill"],
  ["katherine", "catherine", "kate", "katie", "kathy", "cathy", "kat", "katarina", "caterina", "katerina", "catalina", "ekaterini", "kaya"],
  ["mary", "molly", "polly", "maria", "marie", "mia", "mariam", "marija"],
  ["anne", "ann", "anna", "annie", "nancy", "hannah", "ana", "anja", "anka"],
  ["susan", "sue", "susie", "suzanne", "susanna", "susana", "zsuzsa"],
  ["patricia", "pat", "patty", "tricia", "trish", "patrizia"],
  ["jennifer", "jen", "jenny", "jenna", "ginevra"],
  ["jessica", "jess", "jessie"],
  ["rebecca", "becky", "becca", "rebekah"],
  ["victoria", "vicky", "tori", "vittoria", "viktoria"],
  ["alexandra", "alex", "sandra", "sasha", "alessandra", "alejandra", "aleka"],
  ["christina", "christine", "chris", "tina", "kristina", "cristina", "christiane"],
  ["deborah", "debbie", "deb", "debra"],
  ["dorothy", "dot", "dotty", "dolly", "dorothea"],
  ["eleanor", "ellie", "nell", "nora", "eleonora", "eleni", "helen", "helena", "elena", "lena"],
  ["frances", "fran", "frannie", "francesca", "francisca", "francoise"],
  ["josephine", "jo", "josie", "giuseppina", "josefina"],
  ["judith", "judy", "jude", "giuditta"],
  ["kimberly", "kim", "kimmy"],
  ["sarah", "sara", "sally", "sadie"],
  ["sophia", "sophie", "sofia", "sonia"],
  ["theresa", "teresa", "terry", "tess", "tessa", "tracy"],
  ["barbara", "barb", "babs", "barbie", "varvara"],
  ["carolyn", "caroline", "carol", "carrie", "carola", "carolina", "karolina"],
  ["cynthia", "cindy", "cyn"],
  ["diana", "diane", "di", "dianne"],
  ["irene", "irini", "eirini", "irina", "rena"],
  ["georgia", "georgina", "gina", "giorgia"],
  ["joan", "joanna", "joanne", "jo", "giovanna", "juana", "ioanna"],
  ["linda", "lynn", "lindy"],
  ["nicole", "nicky", "nikki", "nicoletta", "nikoleta"],
  ["stephanie", "steph", "stefania", "stefanie", "estefania"],
  ["virginia", "ginny", "ginger", "virginie"],
  ["wilhelmina", "mina", "wilma", "billie"],
  ["angela", "angie", "angelina", "angeliki", "angelica"],
  ["siobhan", "shavon", "shevaun", "chevonne", "shivaun"],
  ["sean", "shawn", "shaun", "shane"],
  ["darren", "daren", "darrin", "darin"],
];
